baseURL = 'https://example.org/'
languageCode = 'en'
title = 'My New Hugo Site'
theme = 'hugo-theme-reimu'

newContentEditor = "content/blog"  # 使用直接赋值格式

# ===== 修正后的配置 =====
[pagination]
  pagerSize = 10  # 使用新的分页配置

[params]
  # 指定在首页显示的内容类型
  mainSections = ["blog"]  # 必须与 newContentEditor 的目录名一致

[frontmatter]
  defaultContentType = "blog"  # 与 mainSections 匹配
# =====================

defaultContentLanguage = 'zh-CN'
[languages]
[languages.en]
languageName = 'English'
weight = 1
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
[languages.zh-TW]
languageName = '繁體中文'
weight = 1
hasCJKLanguage = true
[languages.ja]
languageName = '日本語'
weight = 1
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true