baseURL = 'https://example.org/'
languageCode = 'en'
title = 'My New Hugo Site'
theme = 'hugo-theme-reimu'

# ↓↓↓ 这里是修改的关键 ↓↓↓
newContentEditor = "content/blog"  # 使用直接赋值格式

# ===== 新增的配置 =====
[params]
  # 指定在首页显示的内容类型（与您的文章目录匹配）
  mainSections = ["blog"]  # 重要：必须与 newContentEditor 的目录名一致

# 设置默认内容类型
[frontmatter]
  defaultContentType = "blog"  # 与 mainSections 匹配

# 配置分页（首页文章列表）
[paginate]
  paginate = 10  # 每页显示文章数量
  home = "/"     # 首页路径
# =====================

defaultContentLanguage = 'zh-CN'
[languages]
[languages.en]
languageName = 'English'
weight = 1
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
[languages.zh-TW]
languageName = '繁體中文'
weight = 1
hasCJKLanguage = true
[languages.ja]
languageName = '日本語'
weight = 1
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true